module.exports = {
    USER_LOGGED_IN: "USER_LOGGED_IN",
    USER_LOGGED_OUT: "USER_LOGGED_OUT",
    SET_ACTIVE_PROJECT: "SET_ACTIVE_PROJECT",
    SET_ACTIVE_TAG_PROJECT: "SET_ACTIVE_TAG_PROJECT",
    SET_USER_PROFILE_NAME: "SET_USER_PROFILE_NAME",
    SET_POST_LIST: "SET_POST_LIST",
    SET_POST: "SET_POST",
}
